### PR TITLE
Fix for escrow race condition

### LINKED ISSUE #68: Race condition between bill escrow and logouts
If a bill gets inserted into the validator during the logout sequence, the unit may lock up, neither stacking nor rejecting the bill. This is due to the mdb server believing that the Q1 XX message sent from the P115 was a response to the D1/D2 messages, and not a separate event.

### PR DESCRIPTION
**Pull request by khoover**
Fixes #68. Note that callbacks for mdb/p115 server requests are all empty, and the response message "Z" is just logged as unrecognized in the soda server.

### CODE REVIEW

File: bob2k14/mdb_server/src/server.ts [hunk 1]
```diff
@@ -237,27 +237,24 @@ class mdb_server {
                                     clearTimeout(mdb.solicit_tm);
                                     cb_temp(null, mdb.last_buffer);
                                 }
-                                else
+                                if (mdb.last_buffer[0] != "X")
```
Comment (jdeblasio) [inline bob2k14/mdb_server/src/server.ts:240]: If I'm being pedantic, this would ideally be an `else if`...

**Review by jdeblasio — APPROVED** [review]
Sure. Why not.

**Comment by jdeblasio** [comment]
Let's deploy this change sometime when you're around-- I don't anticipate any issues, but seeing as it isn't actually tested, it seems prudent to be cautious :-)

**Comment by khoover** [comment]
On that note, how do I test changes?
